//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFModelFirst
{
    using System;
    
    public enum AddressType : int
    {
        Billing = 1,
        Shipping = 2,
        Other = 3
    }
}
